<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day09sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [ ]:
#1
run_sql("""SELECT employee_id, first_name
FROM employees
LIMIT 6;""")

   employee_id first_name
0            1      Aarav
1            2     Vivaan
2            3     Aditya
3            4       Riya
4            5      Priya
5            6       Neha

In [ ]:
#2
run_sql("""SELECT department_id, department_name
FROM departments
LIMIT 5;""")

   department_id department_name
0              1              HR
1              2         Finance
2              3              IT
3              4       Marketing
4              5           Sales

In [ ]:
#3
run_sql("""SELECT product_name, category, price
FROM products
lIMIT 8;""")

     product_name category    price
0  Laptop Model 1   Laptop  90499.0
1  Laptop Model 2   Laptop  90999.0
2  Laptop Model 3   Laptop  91499.0
3  Laptop Model 4   Laptop  91999.0
4  Mobile Model 1   Mobile  30499.0
5  Mobile Model 2   Mobile  30999.0
6  Mobile Model 3   Mobile  31499.0
7  Mobile Model 4   Mobile  31999.0

In [18]:
#4
run_sql("""SELECT customer_id, first_name, email
FROM customers
LIMIT 8;""")

   customer_id first_name             email
0            1      Akash   akash1@mail.com
1            2       Ritu    ritu2@mail.com
2            3      Mohit   mohit3@mail.com
3            4     Simran  simran4@mail.com
4            5       Yash    yash5@mail.com
5            6     Anjali  anjali6@mail.com
6            7     Deepak  deepak7@mail.com
7            8      Komal   komal8@mail.com

In [20]:
#5
run_sql("""SELECT order_id, customer_id, order_date
FROM orders
LIMIT 15;""")

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
5          6           15  2025-09-01
6          7            2  2024-05-15
7          8           13  2026-03-11
8          9           28  2025-01-10
9         10            1  2024-07-16
10        11           13  2024-12-19
11        12           26  2025-12-07
12        13           14  2026-04-14
13        14           33  2024-01-19
14        15           27  2024-10-16

In [23]:
# Bounce Challenge
run_sql("""SELECT product_id, product_name, price
FROM products
LIMIT 5;""")

   product_id    product_name    price
0           1  Laptop Model 1  90499.0
1           2  Laptop Model 2  90999.0
2           3  Laptop Model 3  91499.0
3           4  Laptop Model 4  91999.0
4           5  Mobile Model 1  30499.0