<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day013sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [3]:
#1 Display customers whose city is 'Bangalore' or 'Mumbai'.
run_sql("""SELECT *
FROM customers
WHERE city = 'Bangalore' OR city = 'Mumbai'""")

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2            3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
3           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
4           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
5           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
6           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai

In [4]:
#2 Display product whose category is 'Electronic' OR 'Furniture'.
run_sql("""SELECT *
FROM products
WHERE category = 'Electronic' OR category = 'Funiture'""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [5]:
#3 Dispaly employees whose department_id is 1 OR 2.
run_sql("""SELECT *
FROM employees
WHERE department_id = 1 OR department_id = 2;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
2,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
3,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
4,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
5,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com

In [8]:
#4 Display order placed by customer_id 1 OR customer_id 2.
run_sql("""SELECT *
FROM orders
WHERE customer_id =1 OR customer_id = 2;""")

   order_id  customer_id  product_id  order_date  quantity
0         7            2          20  2024-05-15         2
1        10            1          10  2024-07-16         5
2        52            2          23  2026-01-31         4
3        66            2           3  2024-08-03         4

In [10]:
#5 Display first_name, last_name, and email of employees whose department_id is 2 OR employee_id is greater than 8.
run_sql("""SELECT first_name, last_name, email
FROM employees
WHERE department_id = 2 OR employee_id > 8;""")

   first_name last_name                       email
0      Vivaan     Patel   vivaan.patel2@company.com
1        John     Brown     john.brown9@company.com
2        Emma     Kumar    emma.kumar10@company.com
3        Noah     Singh    noah.singh11@company.com
4      Olivia       Roy    olivia.roy12@company.com
5        Liam     Singh    liam.singh13@company.com
6      Sophia       Roy    sophia.roy14@company.com
7      Ananya     Singh  ananya.singh15@company.com
8       Karan    Taylor  karan.taylor16@company.com
9       Rohan     Singh   rohan.singh17@company.com
10      Sneha    Sharma  sneha.sharma18@company.com
11      David     Singh   david.singh19@company.com
12       Sara    Taylor   sara.taylor20@company.com
13      Arjun    Taylor  arjun.taylor21@company.com
14       Isha       Roy      isha.roy22@company.com
15      Kabir    Sharma  kabir.sharma23@company.com
16      Meera     Singh   meera.singh24@company.com
17     Vikram       Roy    vikram.roy25@company.com
18      Nisha    Sharma  nisha.sharma26@company.com
19     Daniel       Roy    daniel.roy27@company.com
20      Grace     Brown   grace.brown28@company.com
21      Aryan       Das     aryan.das29@company.com
22      Pooja    Sharma  pooja.sharma30@company.com

In [13]:
# Bonus Challenge
# Write a query taht returns rows matching either of two differnt values from any table.
run_sql("""SELECT *
FROM products
WHERE category = 'Electronic'
OR category = 'clothing';""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []