<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day11sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [4]:
#1 Display all detalis of the employee whose employee_id is 1.
run_sql("""SELECT *
FROM employees
WHERE employee_id = 1;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com

In [5]:
#2 Display all products whose category is 'Electronics'.
run_sql("""SELECT *
FROM products
WHERE category = 'Electronics';""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [6]:
#3 Display all customers who belong to the belong to city 'Bangalore'.
run_sql("""SELECT *
FROM customers
WHERE city = 'Bangalore';""")

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore

In [7]:
#4 Display all orders placed by customer_id 1.
run_sql("""SELECT *
FROM orders
WHERE customer_id = 1;""")

   order_id  customer_id  product_id  order_date  quantity
0        10            1          10  2024-07-16         5

In [8]:
#5 Display first_name, last_name, and email of employees who belong to department_id 2.
run_sql("""SELECT first_name, last_name, email
FROM employees
WHERE department_id = 2;""")

  first_name last_name                      email
0     Vivaan     Patel  vivaan.patel2@company.com
1     Olivia       Roy   olivia.roy12@company.com
2       Isha       Roy     isha.roy22@company.com

In [13]:
# Bonus Challenge

run_sql("""SELECT *
FROM employees
WHERE employee_id = 5;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com