<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day08sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [5]:
#1
run_sql("""SELECT employee_id, email
FROM employees
LIMIT 5;""")

   employee_id                      email
0            1   aarav.patel1@company.com
1            2  vivaan.patel2@company.com
2            3    aditya.das3@company.com
3            4      riya.das4@company.com
4            5     priya.das5@company.com

In [6]:
#2
run_sql("""SELECT department_name
FROM departments
LIMIT 4;""")

  department_name
0              HR
1         Finance
2              IT
3       Marketing

In [8]:
#3
run_sql("""SELECT product_id, product_name, category
FROM products
LIMIT 6;""")

   product_id    product_name category
0           1  Laptop Model 1   Laptop
1           2  Laptop Model 2   Laptop
2           3  Laptop Model 3   Laptop
3           4  Laptop Model 4   Laptop
4           5  Mobile Model 1   Mobile
5           6  Mobile Model 2   Mobile

In [10]:
#4
run_sql("""SELECT first_name, email, city
FROM customers
LIMIT 8;""")

  first_name             email       city
0      Akash   akash1@mail.com  Bangalore
1       Ritu    ritu2@mail.com  Bangalore
2      Mohit   mohit3@mail.com     Mumbai
3     Simran  simran4@mail.com    Chennai
4       Yash    yash5@mail.com       Pune
5     Anjali  anjali6@mail.com       Pune
6     Deepak  deepak7@mail.com  Hyderabad
7      Komal   komal8@mail.com      Delhi

In [21]:
#5
run_sql("""SELECT order_id, customer_id, order_date
FROM orders
LIMIT 12;""")

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
5          6           15  2025-09-01
6          7            2  2024-05-15
7          8           13  2026-03-11
8          9           28  2025-01-10
9         10            1  2024-07-16
10        11           13  2024-12-19
11        12           26  2025-12-07

In [16]:
# Bounus Challenge
run_sql("""SELECT product_name, price
FROM products""")

          product_name    price
0       Laptop Model 1  90499.0
1       Laptop Model 2  90999.0
2       Laptop Model 3  91499.0
3       Laptop Model 4  91999.0
4       Mobile Model 1  30499.0
5       Mobile Model 2  30999.0
6       Mobile Model 3  31499.0
7       Mobile Model 4  31999.0
8   Headphones Model 1   5499.0
9   Headphones Model 2   5999.0
10  Headphones Model 3   6499.0
11  Headphones Model 4   6999.0
12     Monitor Model 1  16499.0
13     Monitor Model 2  16999.0
14     Monitor Model 3  17499.0
15     Monitor Model 4  17999.0
16    Keyboard Model 1   2499.0
17    Keyboard Model 2   2999.0
18    Keyboard Model 3   3499.0
19    Keyboard Model 4   3999.0
20       Mouse Model 1   1499.0
21       Mouse Model 2   1999.0
22       Mouse Model 3   2499.0
23       Mouse Model 4   2999.0
24      Camera Model 1  46499.0