<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day10sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [3]:
#1 Display unique department names from teh department table.
run_sql("""SELECT DISTINCT department_name
FROM departments;""")

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [5]:
#2 Display unique city values from the customers table.
run_sql("""SELECT DISTINCT city
FROM customers;""")

        city
0  Bangalore
1     Mumbai
2    Chennai
3       Pune
4  Hyderabad
5      Delhi
6    Kolkata

In [7]:
#3 Dispaly unique categery values from the products table.
run_sql("""SELECT DISTINCT category
FROM products;""")

     category
0      Laptop
1      Mobile
2  Headphones
3     Monitor
4    Keyboard
5       Mouse
6      Camera

In [8]:
#4 Display the first 5 unique employee job titles using DISTINCT and LIMIT.
run_sql("""SELECT DISTINCT job_title
FROM employees
LIMIT 5;""")

             job_title
0         HR Executive
1           Accountant
2    Software Engineer
3  Marketing Executive
4      Sales Executive

In [10]:
#5 Display teh first 10unique customer cities usin DISTINCT and LIMIT.
run_sql("""SELECT DISTINCT city
FROM customers
LIMIT 10;""")

        city
0  Bangalore
1     Mumbai
2    Chennai
3       Pune
4  Hyderabad
5      Delhi
6    Kolkata

In [12]:
# Bonus Challege
run_sql("""SELECT DISTINCT phone
FROM customers;""")

         phone
0   9666696518
1   9627404182
2   9208428912
3   9979444461
4   9426111115
5   9693986973
6   9906274295
7   9467566361
8   9899533704
9   9332083015
10  9719551111
11  9658448295
12  9361812679
13  9604314504
14  9702952921
15  9118811611
16  9865412201
17  9504584808
18  9995653703
19  9659589923
20  9124393190
21  9882449902
22  9744597750
23  9185583902
24  9834197053
25  9988357959
26  9922832851
27  9110051432
28  9200774016
29  9627755893
30  9750806415
31  9787498671
32  9665152033
33  9642604350
34  9847568100
35  9310837702
36  9413891625
37  9634822466
38  9759424149
39  9829603810